// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAdmin.EntityFramework.Core;

#nullable disable

namespace ZAdmin.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20220330020341_v.1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZAdmin.Core.Entity.SysApp", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("Id主键");

                    b.Property<string>("Active")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("是否默认激活");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("编码");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasComment("创建者Id");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("创建者名称");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("软删除标记");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("名称");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("状态");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.Property<long?>("UpdatedUserId")
                        .HasColumnType("bigint")
                        .HasComment("修改者Id");

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("修改者名称");

                    b.HasKey("Id");

                    b.ToTable("sys_app");

                    b.HasComment("系统应用表");
                });
#pragma warning restore 612, 618
        }
    }
}
